spring.application.name=distributed-outbox-pattern

spring.datasource.url=jdbc:postgresql://localhost:5432/outboxpattern
spring.datasource.username=seetharam
spring.datasource.password=su

spring.jpa.hibernate.ddl-auto=update
